export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SEND_DEBTORS_SUCCESS = "SEND_DEBTORS_SECCESS";

export const FETCH_DEBTORS_SUCCESS = "FETCH_DEBTORS_SUCCESS";